Repository Elise-Jones/rancidtomatillos, pull requests merged in 2023-07, with the labels that each got.

#10 Feature/display all movies
  public/index.html
  src/App.css
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.css
  src/Card/Card.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/index.css
  src/index.js
  src/sampleData.js
Labels: enhancement

#17 Feature/network requests
  src/App/App.js
  src/Card/Card.js
  src/apiCalls.js
Labels: enhancement

#27 Feature/proptypes
  package-lock.json
  package.json
  src/Card/Card.js
  src/Gallery/Gallery.js
  src/Movie/Movie.js
Labels: enhancement

#31 Feature/router
  cypress.config.js
  cypress/e2e/app_spec.cy.js
  cypress/e2e/gallery_spec.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/movie.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/Card/Card.css
  src/Card/Card.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/Movie/Movie.js
  src/index.css
  src/index.js
Labels: enhancement

#34 Feature/css
  public/index.html
  src/App/App.css
  src/Card/Card.css
  src/Card/Card.js
  src/Gallery/Gallery.css
  src/Gallery/Gallery.js
  src/Movie/Movie.css
  src/Movie/Movie.js
  src/index.css
Labels: enhancement

#37 Fix/proptypes
  src/App/App.js
  src/Card/Card.js
  src/Gallery/Gallery.js
  src/Movie/Movie.js
Labels: bug

#42 Feature/error handling
  cypress/e2e/gallery_spec.cy.js
  src/App/App.js
  src/Error/Error.js
  src/apiCalls.js
Labels: enhancement

#47 Feature/responsive design
  cypress/e2e/gallery_spec.cy.js
  src/Card/Card.css
  src/Error/Error.css
  src/Error/Error.js
  src/Gallery/Gallery.css
  src/Movie/Movie.css
  src/Movie/Movie.js
  src/index.css
Labels: enhancement

#48 Readme
  README.md
  cypress/e2e/gallery_spec.cy.js
  src/Movie/Movie.css
  src/Movie/Movie.js
Labels: documentation

#49 Refactor cypress tess using alias/wait
  cypress/e2e/gallery_spec.cy.js
  cypress/support/commands.js
Labels: enhancement
